name: update stars
on:
  schedule:
    - cron: '0 6 * * *' 
  workflow_dispatch: {}

jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ env.REPOSITORY_NAME }}
          USERNAME: ${{ github.repository_owner }}
        run: node update-stars.js